# By Harsh H. Rajpurohit
name: Privado_Vpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  google_mobile_ads: ^5.0.0 
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.4.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  http: ^1.2.1
  vpn_connection_detector: ^1.0.6
  csv: ^6.0.0
  flutter_launcher_icons: ^0.13.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/images/ic_launcher.png"

  # Change package name  
  # change_app_package_name: ^1.1.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/animations/